nyaruka/gocommon

urns/urns.go
urns/urns_test.go

Need the facebook ref stuff for courier dealing with mapping these back to real facebook ids. Decided to just bump coverage to 100% while I was at it.

Add facebook ref code, get to 100% coverage

---

urns/urns.go
urns/urns_test.go

Need `ValidSchemes` in goflow to get the list of all allowed schemes

Add URN.Format() and export ValidSchemes

---

urns/urns.go
urns/urns_test.go

we should be return an err when the urn path is ""

Always Validate the URN  return err if it is not valid

---

urns/urns.go
urns/urns_test.go

`cellbroadcastchannel50` is a tel URN we are seeing.

Increase possible tel length

---

urns/urns.go
urns/urns_test.go

First PR for adding FreshChat support. the URN for freshchat will be `freshchat:user_uuid?channel_uuid`

Add FreshChat URN

---

urns/urns.go

I am sending this PR to the demand that emerged in issue [#1125](https://github.com/rapidpro/rapidpro/issues/1125).

Add VK scheme

---

dates/date.go
dates/date_test.go
dates/now.go
dates/now_test.go
dates/timeofday.go
dates/timeofday_test.go
dates/utils.go
dates/utils_test.go
go.mod
go.sum
httpx/access.go
httpx/access_test.go
httpx/http.go
httpx/http_test.go
httpx/mock.go
httpx/mock_test.go
httpx/retries.go
httpx/retries_test.go
jsonx/json.go
jsonx/json_test.go
random/rand.go
random/rand_test.go

Does https://github.com/nyaruka/gocommon/issues/21

Move some util packages from goflow

---

gsm7/gsm7.go
gsm7/gsm7_test.go

Before there's any more divergence

📱 Merge and move gsm7 packages from mailroom and courier

---

urns/urns.go

https://github.com/nyaruka/rapidpro/pull/3040

Add RocketChat scheme

---

storage/s3.go
storage/s3_test.go

Include AWS region in storage URLs

---

urns/urns.go
urns/urns_test.go

this new urn is needed for that PR nyaruka/courier#372 in Courier

add weniwebchat urn

---

random/rand.go
random/rand_test.go

Fixes https://sentry.io/organizations/nyaruka/issues/2867297207/?project=1285856

Make random functions threadsafe

---

urns/urns.go
urns/urns_test.go

According to [issue](https://github.com/rapidpro/rapidpro/issues/1516) and PR opened on [Courier](https://github.com/nyaruka/courier/pull/392) repository.

Supports Instagram URN 

---

storage/s3.go

https://sentry.io/organizations/nyaruka/issues/2971922130/?project=1281372&referrer=alert_email

Fix race condition in S3Storage.BatchPut

---

urns/urns.go
urns/urns_test.go

https://github.com/rapidpro/rapidpro/issues/1661

Add Slack Scheme

---

urns/urns.go
urns/urns_test.go

https://github.com/rapidpro/rapidpro/issues/1661

Add URN for Teams channel

---

.github/workflows/ci.yml
dbutil/utf8.go
dbutil/utf8_test.go

Which takes care of removing null characters that PG can't cope with

Add `dbutil.ToValidUTF8`

---

dbutil/null.go
dbutil/null_test.go
dbutil/query_test.go

Now that golang has generics.. now that we have this repo.. I'm on the fence about whether it's worth putting this stuff in nyaruka/null so for now just putting some functions that we need in goflow, here.

Add util functions for working with nullable string types

---

analytics/base.go
dates/format.go
dates/parse.go
dbutil/bulk.go
dbutil/errors_test.go
dbutil/scan.go
go.mod
go.sum
httpx/access.go
httpx/http.go
httpx/mock.go
httpx/recorder.go
i18n/language.go
storage/s3.go
urns/phone.go

github.com/pkg/errors has been archived for the last 3.5 years....

Use std library for errors

---

aws/dynamo/writer.go
aws/dynamo/writer_test.go
syncx/batcher.go
syncx/batcher_test.go

Otherwise tests have to do a lot of waiting

Add `Batcher.Flush` and `Writer.Flush`
