nyaruka/gocommon

urns/urns.go
urns/urns_test.go

mailroom logs have a bunch of errors from android channels receiving URNs that are two digits, so ya, those are a thing.
As an aside.. should this package just be part of courier maybe? Go will take care of only pulling in the appropriate parts no?

allow single digit shortcodes for tel URNs

---

urns/urns.go
urns/urns_test.go

Provides a way to make a URN from a string that might not be strictly valid, but at least has the right structure

Add urns.Parse function

---

.github/workflows/ci.yml
CHANGELOG.md

This adds a URN type for Discord IDs. This enables courier to send/receive messages to/from the standalone discord proxy.
See:
https://github.com/rapidpro/rapidpro/issues/1252

Discord ID URN type

---

urns/utils.go
urns/utils_test.go

Need to be careful leaning on `phonenumbers.IsPossibleNumber` since it includes local only numbers https://github.com/nyaruka/phonenumbers/blob/5cebec5f23b923a5ffab981e9b1922fa650497b1/phonenumbers.go#L2265

📵 ParseNumber should ignore numbers which are only possible as local numbers

---

httpx/recorder.go
httpx/recorder_test.go

Inbound request tracing is a bit annoying in go because `r.Body` is a stream and reading it destroys it. We use Recorder in a few places in mailroom but get into trouble where downstream items read the body of the request without first cloning it. That seems like that really should be a concern of the recorder and not downstream clients of the request, so this adds a `SaveRequest` method on Recorder which immediately saves the request trace for later use as a trace. Made this an option since I know we use Recorder in places where large request bodies can be a problem. (we'll just insert this here on the mailroom side to guarantee we are getting the whole request for ivr items: https://github.com/nyaruka/mailroom/blob/master/web/ivr/ivr.go#L36)

Add option to save request immediately after creating recorder

---

httpx/mock.go
httpx/mock_test.go

So we can write..
```json
{"status": 202, "body": {"foo": "bar"}}
```
instead of..
```json
{"status": 202, "body": "{\"foo\": \"bar\"}"}
```
when bodies are JSON

Allow http mocks in JSON to use actual JSON for the body

---

gsm7/gsm7.go
gsm7/gsm7_test.go

FF should be `\f`, instead of ' ', space, to calculate segment correctly.

gsm7: Fix U+000C, form feed(\f), instead of space, for 0x0A

---

jsonx/json.go
jsonx/json_test.go

Useful in tests but also I think fine to use in select places where we assume things can't error

Add Must* versions of jsonx.Marshal and jsonx.Unmarshal

---

httpx/http.go
httpx/http_test.go

In addition to ignoring invalid UTF8. Turns out Postgres really doesn't like null chars: https://www.commandprompt.com/blog/null-characters-workarounds-arent-good-enough/

🛀 Add support for sanitizing a response trace by stripping nulls

---

syncx/sync.go
syncx/sync_test.go

Would use this for locking around media URL lookups in mailroom or courier. We want simultaneous lookups of a given url to always be synchronized. It doesn't matter if lookups for a different url occasionally share the same locking, but generally we don't want a lookup of url A to block lookups of urls B, C etc.

Add `syncx.HashedMutexMap`

---

storage/base.go
storage/fs.go
storage/fs_test.go
storage/s3.go
storage/s3_test.go

So that the `Storage` interface is completely storage type agnostic

Storage types should have object permissions/acl set via constructor

---

go.mod
go.sum
syncx/batcher.go
syncx/batcher_test.go

If for example courier has 1000 msg statuses queued, batcher shouldn't wait to hit timeout.. should just process those 1000.

Rework `syncx.Batcher` so that it flushes a batch without waiting if it has enough items

---

httpx/websocket.go
httpx/websocket_test.go

Addresses https://github.com/nyaruka/gocommon/issues/109

Fix controlled closing of websockets

---

urns/schemes.go
urns/urns.go
urns/urns_test.go

Currently goflow generates editor auto-completion by title casing scheme prefixes.. this adds name to scheme objects so we can easily get...
* `LINE` instead of `Line`
* `WhatsApp` instead of `Whatsapp`
* `Email` instead of `mailto`

Add names to schemes and make `urns.Schemes()` return full Scheme objects

---

urns/phone.go
urns/schemes.go
urns/urns.go
urns/urns_test.go

1. Tweak `urns.NewFromParts` so scheme is a string
2. Export the `urns.Schemes` slice instead of exposing via function

URN schemes tweaks (from trying to upgrade goflow)

---

elastic/query.go
elastic/query_test.go
elastic/sort_test.go

Update elastic query DSL syntax

---

.github/workflows/ci.yml
s3x/s3.go
s3x/s3_test.go
s3x/urls.go
s3x/urls_test.go

We're moving away from storages which can be filesystem for testing, S3 for prod... and using S3 clients for everything with minio for local development and CI (and prod if anyone wants).

Add new s3x package to replace storage

---

aws/cwatch/service.go
aws/cwatch/service_test.go

Doesn't make sense to queue and batch for something like indexer.. it generates a handful of metrics every 5 seconds

Make batch queue processing optional on cloudwatch service

---

aws/cwatch/service.go
aws/cwatch/service_test.go

Cuz unit tests shouldn't need to start and stop the queue stuff...

Add special handling deployment=test in cloudwatch service

---

aws/dynamo/spool.go
aws/dynamo/spool_test.go
aws/dynamo/writer.go
aws/dynamo/writer_test.go
syncx/batcher.go
syncx/batcher_test.go

For `syncx.Batcher`, `dynamo.Writer` and `dynamo.Spool`, pass `WaitGroup` via start method

---

aws/dynamo/spool.go
aws/dynamo/spool_test.go
aws/dynamo/writer.go
aws/dynamo/writer_test.go

Otherwise it's more work for callers to ensure writers are fully stopped before spools

Rework stopping writers and spools to be synchronous
